name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Проверка исходного кода
    - uses: actions/checkout@v4

    # Шаг 2: Логин в Docker Hub (или другой реестр)
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Шаг 3: Сборка Docker-образа
    - name: Build the Docker image
      run: |
        IMAGE_NAME=arai9/project
        TAG=$(date +%Y%m%d%H%M%S)
        docker build . --file Dockerfile --tag $IMAGE_NAME:$TAG

    # Шаг 4: Загрузка образа в Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_NAME=arai9/project
        TAG=$(date +%Y%m%d%H%M%S)
        docker push $IMAGE_NAME:$TAG
